// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinballPVP.Api.Data;

#nullable disable

namespace PinballPVP.Api.Migrations
{
    [DbContext(typeof(PinballPVPContext))]
    [Migration("20260608101227_DesktopMigration")]
    partial class DesktopMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PinballPVP.Api.Models.PlayerRecord", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("SoloHighscore")
                        .HasColumnType("integer")
                        .HasColumnName("solo_highscore");

                    b.Property<int>("SoloLosses")
                        .HasColumnType("integer")
                        .HasColumnName("solo_losses");

                    b.Property<int>("SoloWins")
                        .HasColumnType("integer")
                        .HasColumnName("solo_wins");

                    b.Property<int>("VersusHighscore")
                        .HasColumnType("integer")
                        .HasColumnName("versus_highscore");

                    b.Property<int>("VersusLosses")
                        .HasColumnType("integer")
                        .HasColumnName("versus_losses");

                    b.Property<int>("VersusWins")
                        .HasColumnType("integer")
                        .HasColumnName("versus_wins");

                    b.HasKey("UserId")
                        .HasName("pk_player_records");

                    b.ToTable("player_records", (string)null);
                });

            modelBuilder.Entity("PinballPVP.Api.Models.SoloMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("final_score");

                    b.Property<bool>("HasWon")
                        .HasColumnType("boolean")
                        .HasColumnName("has_won");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_won");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_solo_matches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_solo_matches_user_id");

                    b.ToTable("solo_matches", (string)null);
                });

            modelBuilder.Entity("PinballPVP.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("ix_users_nickname");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PinballPVP.Api.Models.VersusMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LoserFinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("loser_final_score");

                    b.Property<int>("LoserId")
                        .HasColumnType("integer")
                        .HasColumnName("loser_id");

                    b.Property<int>("LoserRoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("loser_rounds_won");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("WinnerFinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("winner_final_score");

                    b.Property<int>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.Property<int>("WinnerRoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("winner_rounds_won");

                    b.HasKey("Id")
                        .HasName("pk_versus_matches");

                    b.HasIndex("LoserId")
                        .HasDatabaseName("ix_versus_matches_loser_id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_versus_matches_winner_id");

                    b.ToTable("versus_matches", (string)null);
                });

            modelBuilder.Entity("PinballPVP.Api.Models.PlayerRecord", b =>
                {
                    b.HasOne("PinballPVP.Api.Models.User", "User")
                        .WithOne("PlayerRecord")
                        .HasForeignKey("PinballPVP.Api.Models.PlayerRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_records_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PinballPVP.Api.Models.SoloMatch", b =>
                {
                    b.HasOne("PinballPVP.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solo_matches_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PinballPVP.Api.Models.VersusMatch", b =>
                {
                    b.HasOne("PinballPVP.Api.Models.User", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versus_matches_users_loser_id");

                    b.HasOne("PinballPVP.Api.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versus_matches_users_winner_id");

                    b.Navigation("Loser");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PinballPVP.Api.Models.User", b =>
                {
                    b.Navigation("PlayerRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
